# Generated by Django 3.2.7 on 2021-10-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
