# Generated by Django 3.2.7 on 2021-10-02 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='uuid',
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, max_length=1000)),
                ('entries', models.ManyToManyField(blank=True, related_name='entries', to='notes.Entry')),
                ('users', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.log'),
        ),
    ]
