# Generated by Django 3.2.7 on 2021-10-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_user_accessible_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accessible_logs',
        ),
    ]
