# Generated by Django 3.2.7 on 2021-10-02 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_user_accessible_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessible_logs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_logs', to='notes.loglist'),
        ),
    ]
