# Generated by Django 3.2.7 on 2021-10-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_user_accessible_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogList',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='accessible_logs',
        ),
    ]
