# Generated by Django 3.2.7 on 2021-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20211002_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logs',
            field=models.ManyToManyField(blank=True, related_name='user_logs', to='notes.Log'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
