# Generated by Django 3.2.7 on 2021-10-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
